version: "3.9"

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: rashad
      POSTGRES_PASSWORD: rashad
      POSTGRES_DB: recipe_bot
    ports:
      - "5432:5432"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
