
-- ----------------------------
-- Schema recipe_bot
-- ----------------------------

CREATE SCHEMA IF NOT EXISTS recipe_bot;

-- ----------------------------
-- Table users
-- ----------------------------

CREATE TABLE IF NOT EXISTS recipe_bot.users (
    user_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    telegram_id INTEGER NOT NULL UNIQUE,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50),
    username VARCHAR(50),
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
    );

-- ----------------------------
-- Table categories
-- ----------------------------

CREATE TABLE IF NOT EXISTS recipe_bot.categories (
    category_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name VARCHAR(50) NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
    );

-- ----------------------------
-- Table areas
-- ----------------------------

CREATE TABLE IF NOT EXISTS recipe_bot.areas (
    area_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    area_name VARCHAR(50) NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
    );

-- ----------------------------
-- Table recipes
-- ----------------------------

CREATE TABLE IF NOT EXISTS recipe_bot.recipes (
    recipe_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipe_name VARCHAR(100) NOT NULL,
    instructions TEXT NOT NULL,
    image_url TEXT,
    video_url TEXT,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW(),
    ingredients TEXT[],
    measurements TEXT[],
    category_id INTEGER NOT NULL REFERENCES recipe_bot.categories(category_id) ON DELETE RESTRICT,
    area_id INTEGER NOT NULL REFERENCES recipe_bot.areas(area_id) ON DELETE RESTRICT
    );

-- ----------------------------
-- Table favorites
-- ----------------------------

CREATE TABLE IF NOT EXISTS recipe_bot.favorites (
    favorite_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES recipe_bot.users(user_id) ON DELETE CASCADE,
    recipe_id INTEGER NOT NULL REFERENCES recipe_bot.recipes(recipe_id) ON DELETE CASCADE,
    created_at TIMESTAMP DEFAULT NOW()
    );

-- Add indexes
CREATE INDEX idx_recipes_name ON recipe_bot.recipes(recipe_name);
CREATE INDEX idx_recipes_category_id ON recipe_bot.recipes(category_id);
CREATE INDEX idx_recipes_area_id ON recipe_bot.recipes(area_id);
CREATE INDEX idx_favorites_user_id ON recipe_bot.favorites(user_id);
CREATE INDEX idx_favorites_recipe_id ON recipe_bot.favorites(recipe_id);